name: HA Config Exporter Updater
version: 0.1.0
slug: ha_config_exporter_updater
description: Private source updater for HA Config Exporter
url: https://github.com/freezejcavi/ha-config-exporter
arch:
  - aarch64
startup: once
boot: manual
init: false
hassio_api: true
hassio_role: manager
map:
  - type: addons
    read_only: false
options: {}
schema: {}
